# This script is used to process a subfolder of a collection
# A collection will contain the photographs, but also the 3d scans of the sherds
# The 3d scans were processed by the p3d software to output a tiff profile drawing.  The p3d software creates
# subfolders within its folder hierarchy depending on the part of the vessel - sherds without a rim or with a handle are also dealt with here,
# but the default is just a plain rim sherd.
source("../01_include/subfolder.R")

# This script will process an entire collection folder, after p3d has been run on all sherds.  Each sherd is a subfolder based on its itemid.
dirList <- list.dirs(path=scanBasePath, full.names=FALSE, recursive=FALSE)
# the 3ds folder is a way to collect all 3d scans, p3d is where the p3d software builds its own folder hierarchy
drawingSubpath<- "/3ds/p3d/Final_drawings/TIFF 600dpi/"
# all p3d projects are called 'a' to keep parallel, the names are automatically generated by p3d
drawingName<-"a   1-8.tif"
# A file prefix is similar to a figureid, in that it provides a way to name individual item files based on the collections' own naming system
filePrefix <- ""

# loop through each of the 3d scan subfolders, one for each item
for(dir in sort(as.numeric(dirList)))
{
  # dig into the p3d folder hierarchy to get to the actual drawing
  drawingPath<- paste(scanBasePath,dir,drawingSubpath,sep="")
  
  oldFile<-""
  
  #print(paste(drawingPath,drawingName,sep=""))
  print(dir)
  # if it is a rim, it will be stored in the base folder
  if (file.exists(paste(drawingPath,drawingName,sep="")))
  {
    oldFile<-paste(drawingPath,drawingName,sep="")
    #print("normal rim")
  } # if it is a sherd without a rim, it gets put in a norim subfolder
  else if (file.exists(paste(drawingPath,"NoRim/",drawingName,sep="")))
  {
    oldFile<-paste(drawingPath,"NoRim/",drawingName,sep="")
    #print("NoRim")
  } # if it is a handle, it gets put in the handle subfolder
  else if (file.exists(paste(drawingPath,"Handle/",drawingName,sep="")))
  {
    oldFile<-paste(drawingPath,"Handle/",drawingName,sep="")
    #print("Handle")
  }
  print(oldFile)
  # copy the drawing over to the main finds folder for drawings and suffix it with the _dwg.tif so the database can find it
  if (oldFile!="")
  {
    file.copy(oldFile,paste(imageBasePath,filePrefix,dir,"_dwg.tif",sep=""))
  }
}